# Generated by Django 3.1.6 on 2022-02-17 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220217_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 10, 51, 0, 718816, tzinfo=utc)),
        ),
    ]
